"""empty message

Revision ID: d1ab0546fe0c
Revises: 6f9c02f0dad1
Create Date: 2023-12-18 15:42:24.939382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ab0546fe0c'
down_revision = '6f9c02f0dad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_images_table', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_car_images_table_car_id_cars_table'), 'cars_table', ['car_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_images_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_car_images_table_car_id_cars_table'), type_='foreignkey')

    # ### end Alembic commands ###
